apiVersion: v1
kind: Service
metadata:
  name: api-rate-limiter-service
  labels:
    app: api-rate-limiter
spec:
  type: LoadBalancer
  selector:
    app: api-rate-limiter
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
